---
driver:
  name: azurerm

driver_config:
  subscription_id: '02555250-2f8d-4ad6-babb-40a853116d2b'
  location: 'southeastasia'
  machine_size: 'Standard_A3'

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2016-datacenter
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[packer::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
