---
driver:
  name: hyperv
  parent_vhd_folder: 'D:\Images\Packer\Virtual Hard Disks'
  parent_vhd_name: 'windows-server-2016-packer.vhdx'

transport:
  username: vagrant
  password: vagrant
  connection_retries: 5
  connection_retry_sleep: 5

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2016-datacenter

suites:
  - name: default
    run_list:
      - recipe[packer::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
