---
driver:
  name: hyperv
  parent_vhd_folder: 'D:\Images'

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-2016-datacenter

suites:
  - name: default
    run_list:
      - recipe[packer::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
